### ISSUE TITLE
Q: Integration with GLFW

### ISSUE THREAD

**Issue by mokiat** [rajveermalviya/go-webgpu#267]
Hi,

I came across this library and would like to plug it into some existing code of mine and get started with WebGPU coding.

My framework is already based on GLFW and I was wondering if there is a trivial way to get `go-webgpu` to work with GLFW?

I see that the examples use `gamen`, however, it does not support some of the features I need (e.g. gamepad input; drag & drop) and would also mean a more substantial rewrite.

**Comment by rajveermalviya** [comment]
Hey,

Sure you can use `go-webgpu` with [glfw](https://github.com/go-gl/glfw).
The examples [boids](https://github.com/rajveermalviya/go-webgpu-examples/tree/main/boids), [cube](https://github.com/rajveermalviya/go-webgpu-examples/tree/main/cube), [triangle](https://github.com/rajveermalviya/go-webgpu-examples/tree/main/boids) and [triangle-msaa](https://github.com/rajveermalviya/go-webgpu-examples/tree/main/boids) use `glfw`. Each of these examples use pretty similar functionality from glfw.

The only quirky thing right now is that glfw doesn't have an extension for webgpu surface initialisation, so we have to do it manually and to do it cross platform way in Go we have to spread the surface creation across multiple go files.
see:
 - [`triangle/surface_darwin.go`](https://github.com/rajveermalviya/go-webgpu-examples/blob/617e1bca694c46d1a9a1662abcbdd5ce8df019ba/triangle/surface_darwin.go)
 - [`triangle/surface_wayland_linux.go`](https://github.com/rajveermalviya/go-webgpu-examples/blob/617e1bca694c46d1a9a1662abcbdd5ce8df019ba/triangle/surface_wayland_linux.go)
 - [`triangle/surface_windows.go`](https://github.com/rajveermalviya/go-webgpu-examples/blob/617e1bca694c46d1a9a1662abcbdd5ce8df019ba/triangle/surface_windows.go)
 - [`triangle/surface_x11_linux.go`](https://github.com/rajveermalviya/go-webgpu-examples/blob/617e1bca694c46d1a9a1662abcbdd5ce8df019ba/triangle/surface_windows.go)

**Comment by mokiat** [comment]
Hi!
Thanks. I was looking at the wrong examples it seems. Sorry about that.

Having these functions available ready for use would be ideal. Aside from making it easy to get started with the library, if there are any issues in the future, they need only be fixed once.

Should I close this issue or will you be using it as reference for future work?

**Comment by rajveermalviya** [comment]
Closing it is fine. I'll mark it as answered

**Comment by rajveermalviya** [comment]
@mokiat I created [wgpuext/glfw](https://pkg.go.dev/github.com/rajveermalviya/go-webgpu/wgpuext/glfw) which provides the surface description creation helpers. Check out the examples for usage: [boids](https://github.com/rajveermalviya/go-webgpu-examples/tree/main/boids), [cube](https://github.com/rajveermalviya/go-webgpu-examples/tree/main/cube), [triangle](https://github.com/rajveermalviya/go-webgpu-examples/tree/main/boids) and [triangle-msaa](https://github.com/rajveermalviya/go-webgpu-examples/tree/main/boids)

**Comment by mokiat** [comment]
@rajveermalviya , thanks. Just had a look and it works very nicely.
